-- AlterTable
ALTER TABLE "gyms" ALTER COLUMN "installationDate" DROP NOT NULL;
ALTER TABLE "gyms" ALTER COLUMN "stateCode" DROP NOT NULL;
ALTER TABLE "gyms" ALTER COLUMN "city" DROP NOT NULL;
ALTER TABLE "gyms" ALTER COLUMN "gymName" DROP NOT NULL;
ALTER TABLE "gyms" ALTER COLUMN "branchCode" DROP NOT NULL;
ALTER TABLE "gyms" ALTER COLUMN "branchTitle" DROP NOT NULL;
ALTER TABLE "gyms" ALTER COLUMN "salesInitial" DROP NOT NULL;
